// AUTO-GENERATED by scripts/parse-xlsx.ts — do not edit manually
import type { EquipmentType, WeightDisplay } from '@/types'

export interface SeedExercise {
  name: string
  category: string
  primaryMuscle: string
  equipmentType: EquipmentType
  weightDisplay: WeightDisplay
  incrementKg: number
  isCustom: boolean
  alternativeExerciseNames: string[]
}

export interface SeedTemplateExercise {
  exerciseName: string
  plannedSets: number
  plannedReps: string
  plannedWeightKg: number | null
  warmupWeights: number[]
  orderInWorkout: number
}

export interface SeedWorkout {
  label: 'A' | 'B' | 'C'
  exercises: SeedTemplateExercise[]
}

export interface SeedWeek {
  weekNumber: number
  isDeload: boolean
  workouts: SeedWorkout[]
}

export const SEED_EXERCISES: SeedExercise[] = [
  {
    "name": "Bench Press",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "barbell",
    "weightDisplay": "per-side",
    "incrementKg": 2.5,
    "isCustom": false,
    "alternativeExerciseNames": ["Push-Up", "Chest Fly Machine", "DB Shoulder Press"]
  },
  {
    "name": "DB Shoulder Press",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "dumbbell",
    "weightDisplay": "per-side",
    "incrementKg": 1.25,
    "isCustom": false,
    "alternativeExerciseNames": ["Over Head Press", "Lateral Raises"]
  },
  {
    "name": "Dumbbell Romanian Deadlift",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "dumbbell",
    "weightDisplay": "per-side",
    "incrementKg": 1.25,
    "isCustom": false,
    "alternativeExerciseNames": ["Dumbbell Lunges", "Squat"]
  },
  {
    "name": "Lat Pulldown",
    "category": "machine",
    "primaryMuscle": "general",
    "equipmentType": "machine",
    "weightDisplay": "total",
    "incrementKg": 5,
    "isCustom": false,
    "alternativeExerciseNames": ["Negative Pull Ups", "Inverted Row", "Barbell Row"]
  },
  {
    "name": "Dumbbell Lunges",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "dumbbell",
    "weightDisplay": "per-side",
    "incrementKg": 1.25,
    "isCustom": false,
    "alternativeExerciseNames": ["Squat", "Dumbbell Romanian Deadlift"]
  },
  {
    "name": "Crunch",
    "category": "bodyweight",
    "primaryMuscle": "general",
    "equipmentType": "bodyweight",
    "weightDisplay": "none",
    "incrementKg": 0,
    "isCustom": false,
    "alternativeExerciseNames": ["Leg Raises", "Deadbug"]
  },
  {
    "name": "Squat",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "barbell",
    "weightDisplay": "per-side",
    "incrementKg": 2.5,
    "isCustom": false,
    "alternativeExerciseNames": ["Dumbbell Lunges", "Dumbbell Romanian Deadlift"]
  },
  {
    "name": "Negative Pull Ups",
    "category": "bodyweight",
    "primaryMuscle": "general",
    "equipmentType": "bodyweight",
    "weightDisplay": "none",
    "incrementKg": 0,
    "isCustom": false,
    "alternativeExerciseNames": ["Inverted Row", "Lat Pulldown"]
  },
  {
    "name": "Lateral Raises",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "dumbbell",
    "weightDisplay": "per-side",
    "incrementKg": 1.25,
    "isCustom": false,
    "alternativeExerciseNames": ["DB Shoulder Press"]
  },
  {
    "name": "Incline Dumbbell Curl",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "dumbbell",
    "weightDisplay": "per-side",
    "incrementKg": 1.25,
    "isCustom": false,
    "alternativeExerciseNames": []
  },
  {
    "name": "Leg Raises",
    "category": "bodyweight",
    "primaryMuscle": "general",
    "equipmentType": "bodyweight",
    "weightDisplay": "none",
    "incrementKg": 0,
    "isCustom": false,
    "alternativeExerciseNames": ["Crunch", "Deadbug"]
  },
  {
    "name": "Over Head Press",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "barbell",
    "weightDisplay": "per-side",
    "incrementKg": 2.5,
    "isCustom": false,
    "alternativeExerciseNames": ["DB Shoulder Press"]
  },
  {
    "name": "Barbell Row",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "barbell",
    "weightDisplay": "per-side",
    "incrementKg": 2.5,
    "isCustom": false,
    "alternativeExerciseNames": ["Inverted Row", "Lat Pulldown"]
  },
  {
    "name": "Chest Fly Machine",
    "category": "machine",
    "primaryMuscle": "general",
    "equipmentType": "machine",
    "weightDisplay": "total",
    "incrementKg": 5,
    "isCustom": false,
    "alternativeExerciseNames": ["Bench Press", "Push-Up"]
  },
  {
    "name": "Overhead Triceps Extension",
    "category": "strength",
    "primaryMuscle": "general",
    "equipmentType": "dumbbell",
    "weightDisplay": "per-side",
    "incrementKg": 1.25,
    "isCustom": false,
    "alternativeExerciseNames": []
  },
  {
    "name": "Deadbug",
    "category": "bodyweight",
    "primaryMuscle": "general",
    "equipmentType": "bodyweight",
    "weightDisplay": "none",
    "incrementKg": 0,
    "isCustom": false,
    "alternativeExerciseNames": ["Crunch", "Leg Raises"]
  },
  {
    "name": "Push-Up",
    "category": "bodyweight",
    "primaryMuscle": "general",
    "equipmentType": "bodyweight",
    "weightDisplay": "none",
    "incrementKg": 0,
    "isCustom": false,
    "alternativeExerciseNames": ["Bench Press", "Chest Fly Machine"]
  },
  {
    "name": "Inverted Row",
    "category": "bodyweight",
    "primaryMuscle": "general",
    "equipmentType": "bodyweight",
    "weightDisplay": "none",
    "incrementKg": 0,
    "isCustom": false,
    "alternativeExerciseNames": ["Negative Pull Ups", "Lat Pulldown", "Barbell Row"]
  }
]

export const SEED_PROGRAM = {
  name: 'Superhero Antrenman Programı',
  totalWeeks: 12,
}

export const SEED_WEEKS: SeedWeek[] = [
  {
    "weekNumber": 1,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5,
              7.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 15,
            "warmupWeights": [
              10,
              10,
              12.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 2.5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 17.5,
            "warmupWeights": [
              10,
              12.5,
              15
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 17.5,
            "warmupWeights": [
              10,
              15
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 2,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 15,
            "warmupWeights": [
              10,
              12.5
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 20,
            "warmupWeights": [
              12.5,
              15,
              17.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 20,
            "warmupWeights": [
              12.5,
              15,
              17.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 15,
            "warmupWeights": [
              10,
              12.5
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 3,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 15,
            "warmupWeights": [
              10,
              10,
              12.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 20,
            "warmupWeights": [
              12.5,
              17.5
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 25,
            "warmupWeights": [
              15,
              17.5,
              22.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 17.5,
            "warmupWeights": [
              10,
              12.5,
              15
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 4,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 17.5,
            "warmupWeights": [
              10,
              15
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 22.5,
            "warmupWeights": [
              12.5,
              15,
              20
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 15,
            "warmupWeights": [
              10,
              10,
              12.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 5,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 15,
            "warmupWeights": [
              10,
              12.5
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 20,
            "warmupWeights": [
              12.5,
              15,
              17.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 6,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 17.5,
            "warmupWeights": [
              10,
              12.5,
              15
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 7,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 15,
            "warmupWeights": [
              10,
              10,
              12.5
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 8,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 9,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 10,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 11,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 12,
    "isDeload": false,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Bench Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "DB Shoulder Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 7.5,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "8",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lat Pulldown",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 30,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Lunges",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Crunch",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "B",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 10,
            "warmupWeights": [
              5,
              7.5
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Lateral Raises",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Incline Dumbbell Curl",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 5,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Leg Raises",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      },
      {
        "label": "C",
        "exercises": [
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 4,
            "plannedReps": "5+",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10,
              10
            ],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 4,
            "plannedReps": "10",
            "plannedWeightKg": 12.5,
            "warmupWeights": [
              7.5,
              10
            ],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Chest Fly Machine",
            "plannedSets": 3,
            "plannedReps": "10-14",
            "plannedWeightKg": 25,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Overhead Triceps Extension",
            "plannedSets": 3,
            "plannedReps": "8-12",
            "plannedWeightKg": 15,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Deadbug",
            "plannedSets": 3,
            "plannedReps": "max",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  },
  {
    "weekNumber": 13,
    "isDeload": true,
    "workouts": [
      {
        "label": "A",
        "exercises": [
          {
            "exerciseName": "Squat",
            "plannedSets": 3,
            "plannedReps": "5",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 0
          },
          {
            "exerciseName": "Bench Press",
            "plannedSets": 3,
            "plannedReps": "5",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 1
          },
          {
            "exerciseName": "Negative Pull Ups",
            "plannedSets": 3,
            "plannedReps": "5",
            "plannedWeightKg": null,
            "warmupWeights": [],
            "orderInWorkout": 2
          },
          {
            "exerciseName": "Over Head Press",
            "plannedSets": 3,
            "plannedReps": "5",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 3
          },
          {
            "exerciseName": "Dumbbell Romanian Deadlift",
            "plannedSets": 3,
            "plannedReps": "5",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 4
          },
          {
            "exerciseName": "Barbell Row",
            "plannedSets": 3,
            "plannedReps": "5",
            "plannedWeightKg": 10,
            "warmupWeights": [],
            "orderInWorkout": 5
          }
        ]
      }
    ]
  }
]
